// GENERATED by scripts/gen-panda-config.py from design/tokens/kodiak.json
// DO NOT EDIT BY HAND. Edit kodiak.json then run: uv run python scripts/gen-panda-config.py
// emitTokensOnly keeps this a pure token layer -- css custom properties only, zero pixels changed.
import { defineConfig } from "@pandacss/dev";

export default defineConfig({
  emitTokensOnly: true,
  preflight: false,
  include: ["./web/kodiak-posts-for-todays-frontier/**/*.{html,js,ts}"],
  exclude: [],
  outdir: "web/kodiak-posts-for-todays-frontier/design/panda",
  theme: {
    extend: {
      tokens: {
        colors: {
          brand: {
            bearBrown: {
              value: "#3B2316",
            },
            blazeOrange: {
              value: "#E8530E",
            },
            frontierGreen: {
              value: "#1A3C34",
            },
          },
          neutral: {
            "0": {
              value: "#FFFFFF",
            },
            "50": {
              value: "#FFF8F0",
            },
            "100": {
              value: "#F4EDE6",
            },
            "200": {
              value: "#E8DDD3",
            },
            "300": {
              value: "#D9CFC6",
            },
            "400": {
              value: "#B8A99E",
            },
            "500": {
              value: "#8C7A70",
            },
            "600": {
              value: "#6B5A53",
            },
            "700": {
              value: "#5A4A42",
            },
            "800": {
              value: "#2E1D14",
            },
            "900": {
              value: "#1A1110",
            },
            "1000": {
              value: "#000000",
            },
          },
        },
        fonts: {
          headline: {
            value: "Rockwell, Clarendon, American Typewriter, Georgia, serif",
          },
          body: {
            value: "Inter, Helvetica Neue, Arial, sans-serif",
          },
          caption: {
            value: "Inter, Helvetica Neue, Arial, sans-serif",
          },
          mono: {
            value: "JetBrains Mono, Menlo, monospace",
          },
        },
        fontWeights: {
          regular: {
            value: 400,
          },
          medium: {
            value: 500,
          },
          bold: {
            value: 700,
          },
          extraBold: {
            value: 800,
          },
        },
        fontSizes: {
          "headline.1x1": {
            value: "56px",
          },
          "headline.9x16": {
            value: "64px",
          },
          "headline.16x9": {
            value: "72px",
          },
          "body.1x1": {
            value: "28px",
          },
          "body.9x16": {
            value: "30px",
          },
          "body.16x9": {
            value: "32px",
          },
          "caption.1x1": {
            value: "22px",
          },
          "caption.9x16": {
            value: "24px",
          },
          "caption.16x9": {
            value: "24px",
          },
        },
        spacing: {
          "0": {
            value: "0px",
          },
          xs: {
            value: "4px",
          },
          sm: {
            value: "8px",
          },
          md: {
            value: "16px",
          },
          lg: {
            value: "24px",
          },
          xl: {
            value: "32px",
          },
          "2xl": {
            value: "48px",
          },
          "3xl": {
            value: "64px",
          },
          "4xl": {
            value: "96px",
          },
          "5xl": {
            value: "128px",
          },
        },
        radii: {
          none: {
            value: "0px",
          },
          sm: {
            value: "4px",
          },
          md: {
            value: "8px",
          },
          lg: {
            value: "16px",
          },
          xl: {
            value: "24px",
          },
          "2xl": {
            value: "32px",
          },
          pill: {
            value: "999px",
          },
        },
        shadows: {
          none: {
            value: "0px 0px 0px 0px #00000000",
          },
          sm: {
            value: "0px 2px 8px 0px #1A111026",
          },
          md: {
            value: "0px 8px 24px 0px #1A111033",
          },
          lg: {
            value: "0px 16px 48px 0px #1A111040",
          },
          bear: {
            value: "0px 12px 32px 0px #3B231633",
          },
          text: {
            value: "0px 2px 4px 0px #000000CC",
          },
        },
      },
      semanticTokens: {
        colors: {
          background: {
            default: {
              value: "{colors.neutral.50}",
            },
            inverse: {
              value: "{colors.brand.bearBrown}",
            },
            accent: {
              value: "{colors.brand.blazeOrange}",
            },
            nature: {
              value: "{colors.brand.frontierGreen}",
            },
          },
          foreground: {
            default: {
              value: "{colors.brand.bearBrown}",
            },
            muted: {
              value: "{colors.neutral.600}",
            },
            inverse: {
              value: "{colors.neutral.50}",
            },
            accent: {
              value: "{colors.brand.blazeOrange}",
            },
          },
          border: {
            default: {
              value: "{colors.neutral.300}",
            },
            strong: {
              value: "{colors.brand.bearBrown}",
            },
            accent: {
              value: "{colors.brand.blazeOrange}",
            },
          },
          overlay: {
            scrim: {
              value: "#1A1110CC",
            },
            scrimAlt: {
              value: "#0000008C",
            },
          },
        },
        spacing: {
          canvasPad: {
            value: "{spacing.2xl}",
          },
          messageBarTop: {
            value: "68%",
          },
          logoOffset: {
            value: "{spacing.lg}",
          },
          accentBarHeight: {
            value: "8px",
          },
        },
      },
    },
  },
});
