"""POST /campaigns/from-photo -- prompt/photo in, branded image out (issue #39 core loop).

The tight core loop only: a prompt (or an uploaded hero) yields a rendered, branded 1x1
(plus 9x16 / 16x9) creative. The 3-language / retail / recipe fan-out is a follow-up and is
not exercised here.

Every assertion runs offline and cred-free: generate_hero falls back to a mock hero with no
Bedrock creds, compose.py renders locally, and no S3 is touched. input_assets is redirected
under tmp_path via the CAP_INPUT_ASSETS_ROOT override so the real dir is never used. The
TestClient cases skip under bare python (no fastapi / no pillow), matching test_assets_upload.py.
"""
import io

import pytest

try:
    from creative_automation.api import HAS_FASTAPI, app
except Exception:  # pragma: no cover - import guard
    HAS_FASTAPI = False
    app = None

try:
    import multipart  # noqa: F401  (python-multipart)

    HAS_MULTIPART = True
except Exception:  # pragma: no cover - import guard
    HAS_MULTIPART = False

try:
    from PIL import Image

    HAS_PIL = True
except Exception:  # pragma: no cover - import guard
    HAS_PIL = False

_CAN_RUN = HAS_FASTAPI and HAS_MULTIPART and HAS_PIL
_SKIP_REASON = "needs fastapi + python-multipart + pillow (bare-python run skips by design)"

ATLANTA = "US-SE-ATL"


def _png_bytes(size: int = 8) -> bytes:
    """A tiny real PNG built in memory -- no fixture file on disk."""
    buf = io.BytesIO()
    Image.new("RGB", (size, size), (59, 35, 22)).save(buf, format="PNG")  # Bear Brown
    return buf.getvalue()


def _client(monkeypatch, tmp_path):
    """A TestClient with S3 disabled and input_assets redirected under tmp_path."""
    from fastapi.testclient import TestClient

    monkeypatch.delenv("DAM_S3_BUCKET", raising=False)
    monkeypatch.delenv("DAM_S3_URI", raising=False)
    monkeypatch.setenv("CAP_INPUT_ASSETS_ROOT", str(tmp_path / "input_assets"))
    return TestClient(app)


def _write_hero(tmp_path, product="power-cakes") -> str:
    """Write a real hero.png under the redirected input_assets root, return its abs path."""
    product_dir = tmp_path / "input_assets" / product
    product_dir.mkdir(parents=True, exist_ok=True)
    hero = product_dir / "hero.png"
    hero.write_bytes(_png_bytes(32))
    return str(hero)


@pytest.mark.skipif(not _CAN_RUN, reason=_SKIP_REASON)
def test_from_prompt_returns_200_and_image_exists(monkeypatch, tmp_path):
    import os

    client = _client(monkeypatch, tmp_path)
    resp = client.post(
        "/campaigns/from-photo",
        json={"prompt": "sunrise trail run with power cakes", "market": ATLANTA},
    )
    assert resp.status_code == 200, resp.text
    body = resp.json()
    # at least one rendered image, and the primary image_path is a real file on disk
    assert body["image_path"]
    assert os.path.exists(body["image_path"])
    assert body["images"], "expected at least one composed image"
    assert os.path.exists(body["images"][0]["image_path"])
    # offline: generated by the mock hero, no Bedrock creds
    assert body["manifest"]["hero_source"].startswith("generated:")


@pytest.mark.skipif(not _CAN_RUN, reason=_SKIP_REASON)
def test_from_hero_path_returns_200_and_image(monkeypatch, tmp_path):
    import os

    client = _client(monkeypatch, tmp_path)
    hero_abs = _write_hero(tmp_path)
    resp = client.post(
        "/campaigns/from-photo",
        json={"hero_path": hero_abs, "product": "power-cakes", "market": ATLANTA},
    )
    assert resp.status_code == 200, resp.text
    body = resp.json()
    assert os.path.exists(body["image_path"])
    # the uploaded photo was used as the hero, not generated
    assert body["manifest"]["hero_source"] == "existing-photo"
    assert body["manifest"]["hero"] == hero_abs


@pytest.mark.skipif(not _CAN_RUN, reason=_SKIP_REASON)
def test_from_asset_id_resolves_uploaded_hero(monkeypatch, tmp_path):
    import os

    client = _client(monkeypatch, tmp_path)
    _write_hero(tmp_path, product="power-cakes")
    resp = client.post(
        "/campaigns/from-photo",
        json={"asset_id": "power-cakes-20250101-deadbeef", "product": "power-cakes"},
    )
    assert resp.status_code == 200, resp.text
    body = resp.json()
    assert os.path.exists(body["image_path"])
    assert body["manifest"]["hero_source"] == "existing-photo"


@pytest.mark.skipif(not _CAN_RUN, reason=_SKIP_REASON)
def test_neither_prompt_nor_hero_returns_400(monkeypatch, tmp_path):
    client = _client(monkeypatch, tmp_path)
    resp = client.post("/campaigns/from-photo", json={"product": "power-cakes"})
    assert resp.status_code == 400
    assert "prompt" in resp.json()["detail"]


@pytest.mark.skipif(not _CAN_RUN, reason=_SKIP_REASON)
def test_market_omitted_defaults_to_atlanta(monkeypatch, tmp_path):
    client = _client(monkeypatch, tmp_path)
    resp = client.post(
        "/campaigns/from-photo",
        json={"prompt": "power cakes on the frontier"},
    )
    assert resp.status_code == 200, resp.text
    body = resp.json()
    assert body["manifest"]["market"] == ATLANTA
    # the default resolves to a real market record in market-languages.json
    assert body["manifest"]["market_known"] is True
    assert body["manifest"]["place"] == "Atlanta, Georgia"


@pytest.mark.skipif(not _CAN_RUN, reason=_SKIP_REASON)
def test_from_prompt_alias_route(monkeypatch, tmp_path):
    import os

    client = _client(monkeypatch, tmp_path)
    resp = client.post(
        "/campaigns/from-prompt",
        json={"prompt": "trailhead breakfast", "market": ATLANTA},
    )
    assert resp.status_code == 200, resp.text
    assert os.path.exists(resp.json()["image_path"])


def test_from_photo_route_registered_when_fastapi_present():
    """Bare-python-safe: when FastAPI is present the routes exist; otherwise skip cleanly."""
    if not HAS_FASTAPI:
        pytest.skip("FastAPI not installed -- endpoint tests skip by design")
    paths = {getattr(r, "path", "") for r in app.routes}
    assert "/campaigns/from-photo" in paths
    assert "/campaigns/from-prompt" in paths
