"""Kodiak art-director brand-voice engine — custom-imported Bedrock model via Strands.

The one job: take a plain art-direction ask ("a hero shot of Power Cakes on a summit at
dawn") and a Kodiak brand voice ("adventurous" | "nourishing"), and return on-brand
caption/voice copy generated by the fine-tuned kodiak-artdirector-1b model. This is the
voice layer — it produces copy, not imagery, so its output goes through the same safety
gate as text_rewriter before it ever leaves the module.

Transport boundary (named, not hidden): exactly one Strands BedrockModel inference against
the custom-imported model ARN. Strands' BedrockModel accepts an imported-model ARN as its
model_id and routes it through the Converse API (llama is converse-compatible). We force
streaming=False so Strands calls the non-streaming converse — custom-imported models serve
converse, not converse_stream. See _try_art_direct for the ModelNotReadyException handling.

    build prompt (### Instruction/### Response) -> Strands converse -> safety gate

Two operational realities are handled here, not swept under a catch block:

1. Scale-to-zero cold start. Custom-imported Bedrock models scale to zero when idle. The
   first invoke after idle raises ModelNotReadyException ("model is warming"). Strands does
   NOT retry this — it re-raises the botocore ClientError. So _try_art_direct wraps the
   Strands call in an explicit backoff loop (RETRY_ATTEMPTS x RETRY_SLEEP_SECONDS) and
   treats ModelNotReadyException as "warming, retry" rather than a hard failure. Every other
   error falls through to the documented offline path.

2. Offline / no-creds. Mirrors text_rewriter: a network-free env-var creds check gates the
   transport call, and when it fails the module returns a deterministic, on-brand mock
   tagged source="mock" so CI stays green with no AWS credentials.

Region note: this model lives in us-west-2 (account bryanchasko-kiro), NOT the us-east-1
the rest of the pipeline uses. So this module carries its OWN region env
(KODIAK_ARTDIRECTOR_REGION) and never falls back to AWS_REGION — pointing the Converse call
at the wrong region would silently not-find the imported model.
"""
from __future__ import annotations

import asyncio
import os
import sys

from . import safety

try:
    from strands.models.bedrock import BedrockModel
except ImportError:  # strands is a hard dep, but keep the import defensive for offline CI
    BedrockModel = None  # type: ignore

try:
    from botocore.exceptions import BotoCoreError, ClientError
except ImportError:  # boto3/botocore are hard deps; defensive for offline CI
    BotoCoreError = ClientError = Exception  # type: ignore

# Voice model: Nova Micro via cross-region inference profile, pay-per-token,
# $0 idle (cost incident 2026-09-23 — the imported 1b copy billed $82.34/day
# in copy-minutes and was deleted). The bare model id rejects on-demand
# Converse in us-west-2; the us.* profile is required. Overridable by env
# for a rebuilt/re-imported custom model.
DEFAULT_MODEL_ARN = "us.amazon.nova-micro-v1:0"
KODIAK_ARTDIRECTOR_MODEL_ARN = os.getenv(
    "KODIAK_ARTDIRECTOR_MODEL_ARN", DEFAULT_MODEL_ARN
)
# Own region on purpose — the model is in us-west-2, the rest of the pipeline is us-east-1.
# Do NOT fall back to AWS_REGION here; a wrong region silently misses the imported model.
KODIAK_ARTDIRECTOR_REGION = os.getenv("KODIAK_ARTDIRECTOR_REGION", "us-west-2")

# The prompt shape the model was fine-tuned on. Deviating from this degrades voice fidelity.
INSTRUCTION_TEMPLATE = "### Instruction:\n{ask}\n\n### Response:\n"

# The voices the model was trained on. Unknown voices still run (the model generalizes) but
# the ask is framed with the closest known intent so offline mocks stay meaningful.
KNOWN_VOICES = ("adventurous", "nourishing")

# Cold-start retry policy — custom-imported models scale to zero and throw
# ModelNotReadyException on the first invoke after idle. Bounded HARD: 2 attempts x
# 1x2s sleep (worst case ~2s of sleep + inference) — one fast warming probe, then
# out. (The old pre-warm Scheduler ping was deleted 2026-09-23: it kept a
# $82.34/day copy charge alive.) PROVEN IN PROD
# (2026-09-08): longer loops blew the wall to rung-D brand-floor on every request
# while the model warmed — a retry must never outlive its caller.
# CI never reaches this path (it has no creds); `sleep` stays injectable for tests.
RETRY_ATTEMPTS = 2
RETRY_SLEEP_SECONDS = 2

# Inference shaping. temperature ~0.4 keeps the brand voice expressive but on-brand.
MAX_TOKENS = 256
TEMPERATURE = 0.4


def _has_creds() -> bool:
    """Cheap, network-free gate before the transport call (mirrors text_rewriter).

    Env-var only on purpose: boto3's get_credentials() can trigger IMDS/SSO lookups with
    multi-second timeouts, which would slow CI and could fire live invokes when ambient
    creds exist. Anything subtler falls to the offline mock path, the safe default.
    """
    return bool(
        os.getenv("AWS_ACCESS_KEY_ID")
        or os.getenv("AWS_PROFILE")
        or os.getenv("AWS_SESSION_TOKEN")
        or os.getenv("AWS_CONTAINER_CREDENTIALS_RELATIVE_URI")
        # Lambda sets the FULL uri, not the relative one — without this the director
        # self-gates to mock even in prod where the execution role has full access.
        or os.getenv("AWS_CONTAINER_CREDENTIALS_FULL_URI")
    )


def _build_ask(ask: str, voice: str) -> str:
    """Frame the raw ask with the requested brand voice, then wrap in the trained template.

    The voice is folded into the instruction text (not a separate field) because the model
    was fine-tuned on a single instruction string. Known voices get a short intent cue; any
    other voice is passed through verbatim so the model can still generalize.
    """
    v = (voice or "adventurous").strip().lower()
    if v == "nourishing":
        framed = f"In Kodiak's nourishing voice (whole-grain, protein, honest): {ask}"
    elif v == "adventurous":
        # Cost-incident fix 2026-09-23: the old "(trail, outdoor, imperative)"
        # descriptor baited recruit-speak ("listen up, recruit") that the
        # military filter then quarantined — guaranteed wasted resamples on
        # any model. The agricultural-frontier lane says the same brand thing
        # in words the filter allows, without prescribing a season or warmth
        # the brief never chose.
        framed = f"In Kodiak's voice (agricultural frontier, honest morning fuel): {ask}"
    else:
        framed = f"In Kodiak's {v} voice: {ask}"
    return INSTRUCTION_TEMPLATE.format(ask=framed)


async def _stream_once(model, prompt: str) -> str:
    """Drive one Strands non-streaming inference and collect the text deltas.

    Strands' model interface is async-generator based even for streaming=False: the single
    converse response is converted into text-delta events. We concatenate the text deltas
    into the completion string. Kept minimal — no Agent, no tools, one turn.
    """
    parts: list[str] = []
    messages = [{"role": "user", "content": [{"text": prompt}]}]
    async for event in model.stream(messages):
        delta = event.get("contentBlockDelta", {}).get("delta", {}) if isinstance(event, dict) else {}
        text = delta.get("text")
        if text:
            parts.append(text)
    return "".join(parts).strip()


def _is_model_not_ready(err: Exception) -> bool:
    """True when the error is the scale-to-zero cold-start signal (warming, not fatal)."""
    resp = getattr(err, "response", None)
    if isinstance(resp, dict):
        return resp.get("Error", {}).get("Code") == "ModelNotReadyException"
    return "ModelNotReadyException" in str(err)


def _try_art_direct(prompt: str, *, region: str, model_arn: str, sleep=None) -> str | None:
    """One Strands inference against the imported-model ARN, with cold-start retry.

    Returns the generated text, or None on any non-recoverable failure so the caller falls
    through to the offline mock. ModelNotReadyException is treated as "warming" and retried
    with backoff up to RETRY_ATTEMPTS; every other error returns None immediately.

    `sleep` is injectable so tests can exercise the retry loop without real waits.
    """
    if BedrockModel is None:
        return None
    _sleep = sleep if sleep is not None else __import__("time").sleep

    # streaming=False forces the non-streaming Converse API — the surface custom-imported
    # models serve. The ARN goes in as model_id; region_name plumbs straight to the client.
    model = BedrockModel(
        model_id=model_arn,
        region_name=region,
        streaming=False,
        max_tokens=MAX_TOKENS,
        temperature=TEMPERATURE,
    )

    last_warming = False
    for attempt in range(1, RETRY_ATTEMPTS + 1):
        try:
            text = asyncio.run(_stream_once(model, prompt))
            return text or None
        except (ClientError, BotoCoreError) as e:
            last_warming = _is_model_not_ready(e)
            if last_warming and attempt < RETRY_ATTEMPTS:
                print(
                    f"[art_director] model warming (ModelNotReadyException), "
                    f"retry {attempt}/{RETRY_ATTEMPTS - 1} after {RETRY_SLEEP_SECONDS}s",
                    file=sys.stderr,
                )
                _sleep(RETRY_SLEEP_SECONDS)
                continue
            if last_warming:
                print("[art_director] voice=warming, skipped — falling back to mock", file=sys.stderr)
            else:
                print(f"[art_director] Strands art-direct fallback: {e}", file=sys.stderr)
            return None
        except Exception as e:  # noqa: BLE001 — documented fallback to offline mock
            print(f"[art_director] Strands art-direct fallback: {e}", file=sys.stderr)
            return None
    return None


def _mock_copy(ask: str, voice: str) -> str:
    """Deterministic, on-brand copy for the offline / no-creds path (source="mock").

    Distinct per known voice so CI output reads brand-appropriate rather than generic. Kept
    ascii, no emoji, no periods-as-filler beyond what reads naturally.
    """
    v = (voice or "adventurous").strip().lower()
    subject = ask.strip().rstrip(".") or "your next adventure"
    if v == "nourishing":
        return (
            f"{subject}: 100% whole grains and real protein, nothing to hide. "
            "Honest fuel for the people you feed."
        )
    if v == "adventurous":
        return (
            f"{subject}. Lace up, head out, and let real food carry you. "
            "Keep it wild."
        )
    return f"{subject}. Real food for real adventures."


def art_direct(
    ask: str,
    voice: str = "adventurous",
    *,
    region: str | None = None,
    model_arn: str | None = None,
) -> dict:
    """Generate Kodiak brand-voice copy for an art-direction ask.

    Args:
        ask: the plain art-direction request (e.g. "a hero shot of Power Cakes at dawn").
        voice: the Kodiak brand voice — "adventurous" or "nourishing" are trained; any other
            string is passed through and the model generalizes.
        region: override the model region (defaults to KODIAK_ARTDIRECTOR_REGION, us-west-2).
        model_arn: override the imported-model ARN (defaults to KODIAK_ARTDIRECTOR_MODEL_ARN).

    Returns:
        {text, source} — text is always safety-gated (redacted if it was not clean). source
        is "bedrock:kodiak-artdirector" on a live inference, else "mock" for the offline path.

    Env vars a caller sets to reach the live model:
        AWS_PROFILE=bryanchasko-kiro   (or AWS_ACCESS_KEY_ID/AWS_SESSION_TOKEN)
        KODIAK_ARTDIRECTOR_REGION=us-west-2                 (default; own region on purpose)
        KODIAK_ARTDIRECTOR_MODEL_ARN=arn:aws:bedrock:...    (default; the live ARN)
    """
    resolved_region = region or KODIAK_ARTDIRECTOR_REGION
    resolved_arn = model_arn or KODIAK_ARTDIRECTOR_MODEL_ARN

    prompt = _build_ask(ask, voice)

    # transport hop — one Strands inference (with cold-start retry), or the offline mock
    generated = (
        _try_art_direct(prompt, region=resolved_region, model_arn=resolved_arn)
        if _has_creds()
        else None
    )
    if generated:
        text = generated
        source = "bedrock:kodiak-artdirector"
    else:
        text = _mock_copy(ask, voice)
        source = "mock"

    # safety hop — always last, never return unsafe text (same gate as text_rewriter)
    check = safety.check_text(text)
    if not check["clean"]:
        text = safety.redact(text)
        check = safety.check_text(text)

    return {"text": text, "source": source, "safety": check}


def _grounded_ask(ask: str, voice: str, examples: list[dict]) -> str:
    """Fold retrieved brand-voice examples into the ask, inside the trained shape.

    Pure function (no network) so grounding is unit-testable. The examples ride
    inside the single instruction string because the model was fine-tuned on one
    instruction field — a separate context field would deviate from the trained
    shape and degrade voice fidelity. Empty examples degrade to the stock ask.
    """
    if not examples:
        return _build_ask(ask, voice)
    lines = [
        "Write in the voice of these real Kodiak brand lines:",
        *[f"- {str(e.get('caption', '')).strip()}" for e in examples[:3]
          if str(e.get("caption", "")).strip()],
        f"Now write for this request: {ask}",
    ]
    return _build_ask("\n".join(lines), voice)


def art_direct_grounded(
    ask: str,
    voice: str = "adventurous",
    *,
    examples: list[dict] | None = None,
    region: str | None = None,
    model_arn: str | None = None,
) -> dict:
    """Grounded director: retrieved brand voice + trained model + safety gate.

    Same transport and safety path as art_direct — the only difference is the ask
    carries retrieved corpus examples. Returns {text, source, safety, grounded,
    example_ids}; grounded is True only when examples were actually folded in.
    source is "bedrock:kodiak-artdirector" on live inference, "mock" offline —
    callers MUST require the live source before letting text near a render.
    """
    examples = [e for e in (examples or []) if str(e.get("caption", "")).strip()][:3]
    prompt = _grounded_ask(ask, voice, examples)
    resolved_region = region or KODIAK_ARTDIRECTOR_REGION
    resolved_arn = model_arn or KODIAK_ARTDIRECTOR_MODEL_ARN

    generated = (
        _try_art_direct(prompt, region=resolved_region, model_arn=resolved_arn)
        if _has_creds()
        else None
    )
    if generated:
        text = generated
        source = "bedrock:kodiak-artdirector"
    else:
        text = _mock_copy(ask, voice)
        source = "mock"

    check = safety.check_text(text)
    if not check["clean"]:
        text = safety.redact(text)
        check = safety.check_text(text)

    return {
        "text": text,
        "source": source,
        "safety": check,
        "grounded": bool(examples),
        "example_ids": [e.get("id") for e in examples],
    }
