"""Precomputed recipe card-DATA emit for the offline Recipes tab.

The kodiak-dev Recipes tab is offline (file://) and cannot call Python live, so
this builds a {market: {month: card_data}} matrix via build_recipe_card_data and
writes it as a JS data file that assigns window.KODIAK_RECIPE_CARDS, matching the
existing window.KODIAK_* offline pattern (web/.../js/data-core.js). Months with no
seeded ingredient emit the honest no-ingredient shape rather than being dropped, so
the frontend can render an honest empty state.

Deterministic: same markets x months -> byte-identical file. The payload carries no
timestamps; only a static build-comment line precedes the assignment.
"""
from __future__ import annotations

import json
from pathlib import Path

from .recipe_card import build_recipe_card_data

_ROOT = Path(__file__).parents[2]
RECIPE_CARDS_JS_PATH = (
    _ROOT
    / "web"
    / "kodiak-posts-for-todays-frontier"
    / "js"
    / "recipe-cards-data.js"
)

# The three probe markets and the full 2026 calendar. US-W-SF is the legacy alias
# resolve_this_month maps to the Pescadero pair.
PROBE_MARKETS = ("US-SE-ATL", "US-W-SF", "US-MW-PARKCITY-84098")
MONTHS_2026 = tuple(f"2026-{m:02d}" for m in range(1, 13))


def build_recipe_cards_matrix(
    markets: tuple[str, ...] | list[str],
    months: tuple[str, ...] | list[str],
) -> dict[str, dict[str, dict]]:
    """Build the {market: {month: card_data}} matrix. Honest null shapes included."""
    matrix: dict[str, dict[str, dict]] = {}
    for market in markets:
        by_month: dict[str, dict] = {}
        for month in months:
            by_month[month] = build_recipe_card_data(market, month=month)
        matrix[market] = by_month
    return matrix


def emit_recipe_cards_js(
    markets: tuple[str, ...] | list[str],
    months: tuple[str, ...] | list[str],
    out_path: str | Path | None = None,
) -> Path:
    """Build the matrix and write it as window.KODIAK_RECIPE_CARDS to a JS file.

    Deterministic: sorted keys, no timestamp in the payload. Returns the path
    written.
    """
    matrix = build_recipe_cards_matrix(markets, months)
    payload = json.dumps(matrix, ensure_ascii=False, indent=2, sort_keys=True)
    out = Path(out_path) if out_path else RECIPE_CARDS_JS_PATH
    out.parent.mkdir(parents=True, exist_ok=True)
    body = (
        "// Precomputed recipe card-DATA for the offline Recipes tab (file://).\n"
        "// Generated by creative_automation.recipe_cards_emit — do not edit by hand.\n"
        "// schema: kodiak/recipe-card@v1 (card-DATA, no image). Deterministic build.\n"
        f"window.KODIAK_RECIPE_CARDS = {payload};\n"
    )
    out.write_text(body, encoding="utf-8")
    return out


def main() -> None:
    """Emit the three probe markets across all 12 months of 2026."""
    path = emit_recipe_cards_js(PROBE_MARKETS, MONTHS_2026)
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
