#!/usr/bin/env python3
"""Build lightweight web derivatives of per-market campaign art.

Source: input_assets/campaign/<MARKET>/{season}-{dish}.png (2016x1152, ~2.5MB
each — far too heavy to ship). Output: 960px-wide JPEGs plus a JS index the
offline page reads with zero fetch:

  web/kodiak-posts-for-todays-frontier/input_assets/campaign-web/<MARKET>/{season}-{dish}.jpg
  web/kodiak-posts-for-todays-frontier/js/campaign-art-index.js  (window.KODIAK_CAMPAIGN_ART)

Season keys on disk (christmas, easter, fall, fourth-of-july, halloween,
thanksgiving) map to months in js; dishes (bars, brownie, muffin, oatmeal-cup,
waffle) map one-to-one onto the five hero tiles. Markets without a campaign
dir keep the Park City resting example — never a broken image.

Usage: uv run python scripts/build-campaign-web-art.py
"""

import json
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "input_assets" / "campaign"
EXTRA_SRC = ROOT / "input_assets" / "oceanside"
WEB = ROOT / "web" / "kodiak-posts-for-todays-frontier"
OUT = WEB / "input_assets" / "campaign-web"
INDEX = WEB / "js" / "campaign-art-index.js"

MAX_W = 960
QUALITY = 68

# months (1-12) each on-disk season key covers; holidays stay available for
# seasonal-moment overrides even though the meteorological default wins.
SEASON_MONTHS = {
    "christmas": [12, 1, 2],
    "easter": [3, 4, 5],
    "fourth-of-july": [6, 7, 8],
    "fall": [9, 10, 11],
    "halloween": [10],
    "thanksgiving": [11],
}

# extras outside the campaign dirs, wired per market below.
EXTRAS = {
    "US-CA-OCEANSIDE": ["oceanside-xmas-blog-turbo.png"],
}


def convert(src: Path, dst: Path) -> None:
    with Image.open(src) as im:
        im = im.convert("RGB")
        if im.width > MAX_W:
            im.thumbnail((MAX_W, MAX_W * 4), Image.LANCZOS)
        dst.parent.mkdir(parents=True, exist_ok=True)
        im.save(dst, "JPEG", quality=QUALITY, optimize=True)


def main() -> None:
    index: dict = {}
    files = 0
    for market_dir in sorted(SRC.iterdir()):
        if not market_dir.is_dir():
            continue
        market = market_dir.name
        seasons: dict = {}
        for png in sorted(market_dir.glob("*.png")):
            stem = png.stem
            # dishes and season keys both contain dashes: match the known dish
            # suffix instead of splitting (oatmeal-cup is one dish).
            dish = next(
                (d for d in ("oatmeal-cup", "bars", "brownie", "muffin", "waffle") if stem.endswith(f"-{d}")),
                "",
            )
            season = stem[: len(stem) - len(dish) - 1] if dish else stem
            dst = OUT / market / f"{season}-{dish}.jpg"
            convert(png, dst)
            seasons.setdefault(season, {})[dish] = (
                f"input_assets/campaign-web/{market}/{season}-{dish}.jpg"
            )
            files += 1
        extras: dict = {}
        for name in EXTRAS.get(market, []):
            src = EXTRA_SRC / name
            if src.exists():
                dst = OUT / market / f"extra-{Path(name).stem}.jpg"
                convert(src, dst)
                extras[Path(name).stem] = (
                    f"input_assets/campaign-web/{market}/extra-{Path(name).stem}.jpg"
                )
                files += 1
        index[market] = {"seasons": seasons, "extras": extras}
    payload = {
        "season_months": SEASON_MONTHS,
        "markets": index,
    }
    INDEX.write_text(
        "// GENERATED by scripts/build-campaign-web-art.py — do not hand-edit.\n"
        f"window.KODIAK_CAMPAIGN_ART = {json.dumps(payload, indent=1)};\n",
        encoding="utf-8",
    )
    print(f"{files} derivatives + index for {len(index)} markets -> {OUT}")


if __name__ == "__main__":
    main()
